POST http://localhost:3000/auth/signup 
Content-Type: application/json

{
   "email": "test@test.ma",
   "password": "123456"
}

### sign in
POST http://localhost:3000/auth/signin 
Content-Type: application/json

{
   "email": "test@test.ma",
   "password": "123456"
}

### logout
POST http://localhost:3000/auth/logout 
Content-Type: application/json

{}

### get the current user
GET http://localhost:3000/auth/whoami